# Generated by Django 5.2.3 on 2025-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_design_possible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
