# Generated by Django 5.2.3 on 2025-07-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_custom_design_possible_product_feature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric',
        ),
    ]
